<?php
	require_once("app/config.php");
	require_once("app/const.php");
	require_once("model.class.php");
	require_once("app.class.php");
	require_once("route.class.php");
	require_once("functions.php");
	require_once("app/routes.php");
?>